name: Template

on:
  push:
    paths:
      - templates/**
      - .github/markdown-templates/**
      - .github/scripts/**
      - README.md
    branches:
      - main
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@main
        
      - name: Add Badge Template include start and end lines
        shell: pwsh
        run: |
          Copy-Item 'README.md' -Destination 'README_COPY.md'
          $readme_path = ‘README_COPY.md’;
          $SELECT_START_STRING = Select-String -Path $readme_path -Pattern "<!-- START PavanMudigonda/coverage-reporter@main/badge-template.md -->";
          $SELECT_END_STRING = Select-String -Path $readme_path -Pattern "<!-- END PavanMudigonda/coverage-reporter@main/badge-template.md -->";
          if ( ($SELECT_START_STRING.Length -eq 0) -and ($SELECT_END_STRING.Length -eq 0) )
          {
            Write-Output "Adding badge template start and end line to README markdown";
            $readme_contents = Get-Content $readme_path;
            "<!-- START PavanMudigonda/coverage-reporter@main/badge-template.md -->" + "'n" + "<!-- END PavanMudigonda/coverage-reporter@main/badge-template.md -->” + “`n” + '---' + “`n” + $readme_contents + (Get-Content $readme_path -Raw) | Set-Content $readme_path;
          }
            else
          {
            Write-Output "Already having badge template lines";
          }


      - name: "Dynamic Badge Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          files: |
            README_COPY.md
            README_COPY.md=README.md
            
#  COMMIT BADGES
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Added/Updated readme" || true

#  PUSH BADGE COMMIT
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
