name: Template

on:
  push:
    paths:
      - templates/**
      - .github/markdown-templates/**
      - .github/scripts/**
      - README.md
    branches:
      - main
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@main
        
      - name: "Add Badge Template to existing README.md"
        run: |
          cat templates/reusable-includes.md README.md > temp-reusable-includes.md
          uniq temp-reusable-includes.md uniq-reusable-includes.md
          mv uniq-reusable-includes.md templates/reusable-includes.md
          

      - name: "Dynamic Badge Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          files: |
            templates/reusable-includes.md=README.md
        env:
          GITHUB: ${{ secrets.GITHUB_TOKEN }}

