name: Template

on:
  push:
    paths:
      - templates/**
      - .github/markdown-templates/**
      - .github/scripts/**
      - README.md
    branches:
      - main
  workflow_dispatch:

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "Dynamic Badge Template Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          files: |
            templates/reusable-includes.md=output/reusable-includes.md
          
      - name: "Add Rendered Badge Template to existing README.md"
        run: |
          cat output/reusable-includes.md README.md > TEMP-README.md
          mv -n TEMP-README.md README.md

#  COMMIT BADGES and README.md changes
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Added/Updated badges" || true

#  PUSH BADGE COMMIT
      - name: Push badge commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

